[package]
name = "k2db"
version = "0.1.0"
edition = "2021"


[dev-dependencies]
paste = "1.0.13"
rstest = "0.17.0"

[dependencies]
rand = "0.8.5"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
